[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "pybind11>=2.6"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/kdknn_jax/kdknn_jax_version.py"
